### ISSUE TITLE
Light novel world is not getting chapters

### ISSUE THREAD

**Issue by Rian-Porfirio** [martial-god/Benny-Scraper#52]
When printing some chapters from the light novel it shows an error.
![image](https://github.com/martial-god/Benny-Scraper/assets/119708951/21da18ec-d07a-420d-a220-c505c9207f51)

**Comment by feahnthor** [comment]
As of now this issue was due to a 403 response from their servers refusing our use-agents, I have updated the code to only use `Other` as a quick fix. Having more than one user agent is best as it helps prevent blocking, so this band-aid that is now being used by all sites will need to be fleshed out to maybe only be used on this site.

You can build publish this branch using `dotnet publish -c Release --self-contained true -r win-x64 -o C:\Users\{YOU USERNAME}\Downloads\BennyScraper`
